name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Ruby syntax
        run: find . -name "*.rb" -print0 | xargs -0 -n1 ruby -c
